name: CI Pipeline

on:
  push:
    branches:
      - main    # This triggers the pipeline when code is pushed to the main branch.
  pull_request:
    branches:
      - main    # This triggers the pipeline on pull requests targeting the main branch.

jobs:
  build:
    runs-on: ubuntu-latest    # Runs on the latest Ubuntu environment.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'    

      - name: Install dependencies
        run: npm install    

      - name: Run tests
        run: npm test    


      - name: Deploy to Vercel (Example)
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} 
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
